export enum ROUTES {
  STARTUP = "Startup",
  EXAMPLE = "Example",
  ONBOARDING = "Onboarding",
  LOGINSCREEN = "LoginScreen",
  OTPSCREEN = "OTPScreen",
  REGISTRATION = "Registration",
  TOPIC_SELECTION = "TopicSelection",
  PROFILE = "Profile",
  SEARCH = "Search",
  POST = "Post",
  TREE = "Tree",
  HOME = "Home",
  TABS = "TABS",
  MESSAGES = "Messages",
  NOTIFICATIONS = "Notifications",
  VERIFY_PHONE_NUMBER = "VerifyPhoneNumber",
  SETTINGS_SCREEN = "SettingsScreen",
  EDIT_PROFILE = "EditProfile",
  LOCATION_MODAL = "LocationModal",
  OTHER_USER_PROFILE = "OtherUserProfile",
  CAMERA_PAGE = "CameraPage",
}
